### ISSUE TITLE
请问支持的最大csv文件大小是多少呢

### ISSUE THREAD

**Issue by hardworkRachel** [yaocctao/kaggle-DataVisulization#1]
你好，我传入了一个130+MB的文件一直loading后显示网页无响应，请问支持的最大csv文件大小是多少呢

**Comment by yaocctao** [comment]
您好，这个还没有试过哟，您可以先从小的文件来试一下，这只是个期末demo，实验的环境也是用的比较小的文件

**Comment by hardworkRachel** [comment]
> Owner

好的，感谢您的回复[heart]
